[package]
name = "marclib"
version = "0.1.0"
authors = ["Adrian Neumann <adrian_neumann@gmx.de>"]
edition = "2018"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.5"
